### ISSUE TITLE
rosaria_client dependency on rosaria

### ISSUE THREAD

**Issue by RobertBlakeAnderson** [pengtang/rosaria_client#1]
The current CMakeList and package.xml of rosaria_client do not list rosaria as a dependency. This can cause catkin_make to fail if it attempts to build rosaria_client before BumperState.h has been build in rosaria.

This is solved by adding find_package(rosaria) to CMakeLists.txt and rosaria run and build dependencies to package.xml

**Comment by pengtang** [comment]
Your suggestion is very useful. I'll add that up shortly, thanks!
